wong2/awesome-mcp-servers

README.md

Hi,
I just released a first version of my ClaudeAI mcp-server that interacts with the Obsidian REST API. Feel free to check it out.
Right now, it can list files and search through it but I am actively working towards more features.
Would to be great to have it listed.
Have fun

added obsidian server

---

README.md

Created a simple Bluesky context server that I wanted to share :)

Add bluesky context server

---

README.md

Added Minima project as an example of local RAG with MCP

Added Minima project to community servers 

---

README.md

Youtube: https://www.youtube.com/watch?v=FI-oE_voCpA
GitHub: https://github.com/kiliczsh/mcp-mongo-server
NPM: https://www.npmjs.com/package/mcp-mongo-server

Add mcp-mongo-server package

---

README.md

Adding a Kubernetes server since it didn't look like there was one on the list.

Add Kubernetes MCP server to Community Servers

---

README.md

Hi, just thank you for this awesome.
I just added client list to run these servers.
Thanks.

doc: Added Clients list

---

README.md

Hi Team, 
This addition addresses the need for a versatile document format conversion tool when using Claude.
By leveraging Pandoc's robust capabilities, mcp-pandoc provides developers and users with a streamlined solution for transforming content between popular document formats while maintaining formatting and structure.
Thank you!

feat: Adds mcp-pandoc for Document Format Conversions

---

README.md

Adding link and description for mcp-server-data-exploration

Update README.md to add mcp-server-data-exploration

---

README.md

**search1api-mcp is a server with all tools you need for search**
- search
- news
- crawl
- sitemap

added search1api

---

README.md

A simple REST API and CLI client to interact with [Model Context Protocol (MCP)](https://modelcontextprotocol.io/) servers.

Update README.md and added mcp client for rest and cli..

---

README.md

I've made an MCP server to integrate with apple shortcuts

Add Apple Shortcuts Server

---

README.md

Snowflake database integration with read/write capabilities and insight tracking

Added snowflake integration

---

README.md

Integrates with clojars to get latest clojure deps info

Update README.md inc clojars server

---

README.md

A server for interacting with apache maven

Update README.md add maven deps server

---

README.md

mcp-difyworkflow-server is an mcp server Tools application that implements the query and invocation of Dify workflows, supporting the on-demand operation of multiple custom Dify workflows.

add DifyWorkflow

---

README.md

Adding a new MCP server that provides Google News search capabilities via SerpAPI integration. This server enables LLMs to search and access news articles with language/region support, topic categorization, and comprehensive story coverage.
- Server: google-news
- Changes to: New server implementation with SerpAPI integration
Currently, there is no dedicated news search capability in the MCP ecosystem. This server fills this gap by providing:
- Structured access to news articles and topics
- Multi-language and region support
- Automatic news categorization
- Full story coverage capabilities
These features enable LLMs to better engage with current events and news-related queries.
The server has been extensively tested with Claude Desktop:
- Basic news search queries
- Multi-language …

Add Google News MCP Server

---

README.md

https://github.com/btwiuse/npm-search-mcp-server

Add npm-search-mcp-server

---

README.md

An MCP server application that sends various types of messages to the WeCom group robot.

add mcp-wecombot-server

---

README.md

https://github.com/mcp-connect/mcp-connect
A client that enables cloud-based AI services to access local Stdio based MCP servers by HTTP/HTTPS requests.

add mcp connect

---

README.md

This PR adds the Windows Control MCP server to the community servers list. This server provides programmatic control over Windows system operations through the Model Context Protocol.
- Mouse control with configurable speed and precision
- Keyboard input and key combinations
- Window management (focus, resize, reposition)
- Screen capture capabilities
- Clipboard integration
- Built using [nut.js](https://nutjs.dev/) for reliable system automation
- Implements strong typing and comprehensive error handling
- Includes detailed documentation and usage examples
- Tested primarily on Windows with potential cross-platform compatibility
- Added entry under Community Servers section
- Fixed formatting to maintain consistency with existing entries
- Ensured proper alphabetical ordering
The server …

Add Windows Control MCP server

---

README.md

Added Jira Context MCP Server which is useful for Coding IDE like Cursor IDE to get the issues or bugs or task from Jira assigned to the user and makes cursor ide do the task

Added Jira Context MCP Server

---

README.md

CLI that generates MCP tools based on your Database schema and data using AI and host as REST, MCP or MCP-SSE server

Added CentralMind Gateway - MCP CLI tool

---

README.md

Added official MCP https://github.com/comet-ml/opik-mcp

Added official Comet Opik MCP

---

README.md

Adds MCP server for Fathom Analytics

Adds MCP FA

---

README.md

https://github.com/bytebase/dbhub
Universal database MCP server connecting to MySQL, PostgreSQL, SQLite, DuckDB and etc.

chore: add DBHub

---

README.md

Adding new mcp server to the readme

Add Gentoro MCP Server

---

README.md

Add Algorand MCP to the Awesome MCP list under community servers and fixed a small issue on Android MCP record (extra dash removed)

Update README.md Add Algorand MCP

---

README.md

This adds hass-mcp - a Home Assistant MCP server

Add Home Assistant MCP Server

---

README.md

Creates and modifies Excel workbooks
Manages worksheets and ranges
Handles formatting and styles
Supports charts and pivot tables

add excel mcp server

---

README.md

Added servers - Vibe Check, Gemsuite

Add servers to README.md

---

README.md

Add the official Semgrep MCP server github.com/semgrep/mcp
Semgrep is the most popular open-source security tool

Add official Semgrep MCP server

---

README.md

This pull request includes updates to the `README.md` file to add new MCP servers.
New MCP servers:
* Added **[HackMD](https://github.com/yuna0x0/hackmd-mcp)** MCP server for integrating [HackMD](https://hackmd.io/)'s note-taking platform with AI assistants.
* Added **[AniList](https://github.com/yuna0x0/anilist-mcp)** MCP server for accessing AniList API data.

Add HackMD and AniList MCP

---

README.md

Add Kubernetes MCP server

---

README.md

Test and verified:
https://www.youtube.com/watch?v=UpBH--HEu5w
Powerdrill AI related links and information:
https://powerdrill.ai/
https://www.youtube.com/@powerdrill_ai
https://github.com/powerdrillai

Add Powerdrill AI MCP Server.

---

README.md

- [ done] Place the newly added server in the right position alphabetically.

Add Paypal MCP server to the list

---

README.md

Add Trello MCP Server to the List

---

README.md

add chaitin ip intelligence search mcp server

Add chaitin-ip-intelligence-search-tool

---

README.md

feat: Add ALAPI MCP Server to the List

---

README.md

fix alapi mcp description

---

README.md

TL;DR
Adding DexPaprika MCP server that enables queries like "What are the top 5 most liquid pools for ETH on Uniswap V3?" with Claude responding with real-time volumes, prices, and market metrics.
Links
GitHub: https://github.com/coinpaprika/dexpaprika-mcp
Documentation: https://docs.dexpaprika.com
NPM: https://www.npmjs.com/package/dexpaprika-mcp

Add new, official MCP server - DexPaprika by CoinPaprika

---

README.md

added nerve client

---

README.md

Add tmux-mcp

---

README.md

- [ A] Place the newly added server in the right position alphabetically.

Add AWS awslabs MCP servers to list of avalible Official MCP servers

---

README.md

Add BloodHound MCP server to the list

---

README.md

- [✅] Place the newly added server in the right position alphabetically.

Add YepCode MCP server

---

README.md

The official MCP for [agentset.ai](https://agentset.ai)

Add Agentset MCP

---

README.md

Add RAD Security mcp server

---

README.md

add last9 mcp

---

README.md

Update paths for AWS MCP server links

---

README.md

Add Skyvern to list

---

README.md

Community version of https://nocodb.com/

Add NocoDB MCP

---

README.md

Add CircleCI MCP Server

---

README.md

Add EdgeOne Pages MCP to README

---

README.md

QA Sphere MCP server that enables Large Language Models to interact directly with test management system test cases, supporting AI-powered development workflows and test case discovery.

QA Sphere MCP Server

---

README.md

Add Browser MCP

---

README.md

Add new MCP Toolbox for Databases server

---

README.md

Turns Swagger/OpenAPI defined REST endpoints into an MCP server, includes Langchain/Langflow integration. Focused on adding security and privacy policies to MCP execution.

Add hippycampus

---

README.md

Update README.md. Add godoc-mcp-server

---

README.md

Add Bucket MCP Server

---

README.md

Add Supabase MCP server

---

README.md

This PR adds the Pollinations MCP server to the Community Servers section. Pollinations is a multimodal MCP server that enables AI assistants like Claude to generate images, text, and audio directly.
- Published to npm as `@pollinations/model-context-protocol`
- Provides tools for generating image URLs, base64-encoded images, audio responses, and text generation
- No authentication required, making it simple to use
- Lightweight and compatible with the Model Context Protocol
- Includes Claude Desktop integration script
- The server follows a modular architecture with separate service modules for different functionalities
- Provides a comprehensive API for multimodal content generation
- Designed with a "thin proxy" approach for minimal processing between client and API …

Add Pollinations MCP server to Community Servers section

---

README.md

Add MastraAI servers

---

README.md

Add MCP Trino reference

---

README.md

Add SearXNG MCP server

---

README.md

- [v] Place the newly added server in the right position alphabetically.

Add alibabacloud-dataworks-mcp-server

---

README.md

Add Twilio Alpha MCP

---

README.md

added fb mcp server

---

README.md

Add Netbird MCP server

---

README.md

Add tl;dv into the Official Integrations

---

README.md

Add `videodb-director-mcp`

---

README.md

Add line-bot-mcp-server

---

README.md

Add brightdata-mcp server to README.md

---

README.md

Add WebScraping.AI

---

README.md

Adding the official Norman Finance MCP server

---

README.md

- Adds Currents MCP server
- https://github.com/currents-dev/currents-mcp

chore: add Currents

---

README.md

Tencent Cloud COS MCP Server based on the MCP protocol enables large models to quickly integrate with Tencent Cloud Storage (COS) and Data Processing (CI) capabilities without coding

add  Tencent Cloud  COS MCP

---

README.md

Add Root Signals

---

README.md

Add create-mcp-ts

---

README.md

alphabetically added Maya MCP server

---

README.md

More details: https://github.com/Couchbase-Ecosystem/mcp-server-couchbase

Add Couchbase official MCP server

---

README.md

Adding Canvas LMS

---

README.md

add dbt (Data Build Tool) MCP

---

README.md

- [ x] Place the newly added server in the right position alphabetically.
Plugged.in is a comprehensive proxy server that combines multiple MCP servers into a single interface with extensive visibility features. It provides discovery and management of tools, prompts, resources, and templates across servers, plus a playground for debugging when building MCP servers. Create collections for different clients like Claude Desktop, Cursor, or Cline.
Key features:
• Unified interface for multiple MCP servers
• Discovery and management of tools across servers
• Debugging playground for MCP server development
• Collections creation for different clients
• Social platform for sharing and discovering MCP configurations

Added plugged.in MCP Proxy

---

README.md

docs: add mcp-server-chart of AntV

---

README.md

Add spm-mcp

---

README.md

generate lyrics, song and background music(instrumental).

Mureka-mcp

---

README.md

Add interactive-mcp

---

README.md

add Microsoft Entra ID MCP Server to the Community Server

docs: add Microsoft Entra ID MCP Server to the Community Server

---

README.md

Add Notte MCP to the list

---

README.md

Adding MCP server for Hostinger API.

Add hostinger-api-mcp

---

README.md

Add Taskeract MCP Server

---

README.md

add User Prompt MCP server

---

README.md

Add MCP Aggregator

---

README.md

Adding jetty.io MCP server

---

README.md

Add Squad MCP

---

README.md

Added Official Teradata MCP Server

---

README.md

Added MCP CLI Adapter

---

README.md

Add Trade Agent to README.md

---

README.md

Add shadcn/ui mcp server

---

README.md

Add Campertunity MCP Server

---

README.md

Added VISO TRUST MCP server under official integrations

---

README.md

Add DAISYS MCP Server

---

README.md

Add ntfy-me-mcp server to community servers

---

README.md

Add Google PSE/CSE MCP Server

---

README.md

Update README.md - Add caldav-mcp

---

README.md

🪄 ImageSorcery MCP added

---

README.md

- [X ] Place the newly added server in the right position alphabetically.

Add GrowthBook

---

README.md

fix tmux link formatting

---

README.md

Add Shinkai (Client) to README.md

---

README.md

It's been put in the right place in alphabetical order.

Add PGYER Official MCP Server

---

README.md

Add Alertmanager MCP server

---

README.md

- Place the newly added Coresignal MCP server in the right position alphabetically.

Add Coresignal MCP

---

README.md

Add BGG MCP

---

README.md

Add Buildkite MCP server

---

README.md

This PR adds DropBin (https://dropbin.org/mcp) to the awesome-mcp-servers list. DropBin is a remote SSE MCP server for hosting HTML webpages and sharing content through temporary URLs without authentication.

Add DropBin remote SSE MCP server

---

README.md

Added xcsimctl and xctools

---

README.md

This PR adds the Multi Chat MCP Server to the community servers section.
Multi Chat MCP Server is an open-source Python framework for building AI-powered chat integrations. It features:
- **Google Chat Integration**: Production-ready implementation with comprehensive API coverage
- **Multi-Provider Architecture**: Framework designed to support Google Chat, Slack, Teams and more simultaneously
- **Unique Capability**: Allows AI assistants to interact with multiple chat platforms at once ("ask once, share everywhere")
- **Enterprise Security**: Built for organizational deployment with privacy and security in mind
- **Extensible Design**: Ready-made scaffolding to add support for Slack, Microsoft Teams, and other chat platforms
- **✅ Comprehensive Message Management**: Send, read, update, …

Add Multi Chat MCP Server (Google Chat) to community servers

---

README.md

Add official AllVoiceLab MCP Server to README

---

README.md

Adding Unified Diff MCP Server to the community servers list.
- Beautiful HTML and PNG diff visualization using diff2html
- High-performance processing with Bun runtime  
- Seamless integration with filesystem edit_file dry-run output
- Cross-platform support (Windows/macOS/Linux)
https://github.com/gorosun/unified-diff-mcp

Add Unified Diff MCP Server - HTML/PNG diff visualization tool

---

README.md

Add Alibabacloud DevOps MCP Server

---

README.md

Adding MCP Task Orchestrator - an AI-powered task orchestration server with specialized agent roles and multi-IDE integration.
Features:
- Intelligent task decomposition using LLM reasoning
- Specialist AI roles (Architect, Implementer, Debugger, etc.)
- Seamless integration with Claude Desktop, Cursor IDE, Windsurf, and VS Code
- Persistent workflow state management
- Single-session orchestration

Add MCP Task Orchestrator to Community Servers

---

README.md

Add MKP (Model Kontext Protocol Server for Kubernetes) to the README.md.
MKP is a native Go implementation that allows LLM-powered applications to interact with Kubernetes clusters through direct API integration, providing comprehensive resource management capabilities including:
- List resources supported by the Kubernetes API server
- List clustered and namespaced resources  
- Get resources and their subresources (including status, scale, logs, etc.)
- Apply (create or update) clustered and namespaced resources
- Execute commands in pods with timeout control
- Generic and pluggable implementation using API Machinery's unstructured client
- Built-in rate limiting for protection against excessive API calls
Repository: https://github.com/StacklokLabs/mkp

Add MKP Server to awesome MCP servers list

---

README.md

Update Bright Data repo URL

---

README.md

Add Jean Memory

---

README.md

A FastAPI and MCP service providing Islamic prayer times calculations
[Source](https://github.com/yusufk/salaah-mcp)
**Motivation:**
The Salaah Times MCP server provides accurate Islamic prayer time calculations based on user-provided location data. Including this server will expand the range of data sources available to users of this project, enabling them to access and utilize prayer time information within their applications.
**Description:**
The Salaah Times MCP server is a FastAPI-based service that calculates prayer times using the [islamic\_times](https://github.com/hassantahan/islamic_times) library. It exposes prayer time data through the MCP protocol, making it easily integrable with other MCP-compatible services and frontends.
**Key Features:**
*   **Accurate Prayer Time …

Added Salaah MCP, community MCP contribution

---

README.md

- [x ] Place the newly added server in the right position alphabetically.
Hello! Thanks so much for maintaining this list of MCP servers.
I'm a developer working full time on my MCP server to help coding agents read documentation. It just came out of alpha and I'm eager to share it with more people. 
Please let me know if you have any questions or there's anything I can do to help :)

Add ref.tools MCP server to the list

---

README.md

**MCP Playground** is a web-based MCP client for testing Claude and Gemini models with Remote MCP server integration.
- **Type:** MCP Client
- **Tech:** Next.js, TypeScript, Cloudflare Workers
- **Features:** Dual AI provider support, OAuth authentication, tool restriction controls
- **URL:** https://mcpsplayground.com/chat
- **Use Case:** Testing MCP servers, comparing AI providers, debugging tool implementations

Add MCPs Playground To MCP Clients List

---

README.md

Adding Token Metrics MCP Server to the Official Servers list.
The Token Metrics Model Context Protocol (MCP) server provides comprehensive cryptocurrency data, analytics, and insights through function calling. This server enables AI assistants and agents to access Token Metrics' powerful API for real-time crypto market data, trading signals, price predictions, and advanced analytics.
Github: https://github.com/token-metrics/mcp
Webiste: https://www.tokenmetrics.com

Add Token Metrics MCP Server to Official Servers

---

README.md

Added MCP Plexus to the list of MCP server frameworks. MCP Plexus is a secure and scalable multi-tenant Python framework. It simplifies the deployment of sophisticated MCP servers, enabling robust multi-tenancy, seamless OAuth 2.1 integrations, persistent user authentication, and API key management. Ideal for developing modern, context-rich AI applications while ensuring security and extensibility.

Added MCP Plexus to the list of MCP server frameworks.

---

README.md

Add official Fulcra Context MCP server

---

README.md

feat: add ui-tars browser mcp

---

README.md

Add intlayer MCP server

---

README.md

add Twelve data mcp

---

README.md

Add Routine official MCP server

---

README.md

Add Lazy Toggl MCP server

---

README.md

Add just-every MCP servers for web content extraction and screenshots

---

README.md

Add official CoinGecko MCP to README.md

---

README.md

Added Trello Desktop MCP server

---

README.md

Add Cycode MCP

---

README.md

Add Apache Doris MCP Server

---

README.md

Add InstantDB's official MCP server

---

README.md

Update README.md - Add fetchSERP mcp server

---

README.md

Add Svelte MCP

---

README.md

Add SchemaCrawler to README.md

---

README.md

open source text-to-graphql mcp server

Adding a community server

---

README.md

- [ X] Place the newly added server in the right position alphabetically.

docs: add Yuga Planner to community MCP list

---

README.md

Add IP2Location.io MCP server

---

README.md

Add Wassenger MCP server

---

README.md

- [ x ] Place the newly added server in the right position alphabetically.

Add Kontent.ai MCP

---

README.md

This PR adds the X (Twitter) MCP server to the awesome list.
The X (Twitter) MCP server is an enhanced implementation that provides comprehensive Twitter/X API integration for AI agents through the Model Context Protocol. Key features include:
- **Dual Authentication**: Supports both OAuth 1.0a and OAuth 2.0
- **Media Support**: Post tweets with images and GIFs using appropriate API versions
- **Smart API Handling**: Automatically uses v2 endpoints with v1.1 fallbacks where needed
- **Rate Limiting**: Built-in protection for Twitter's free tier limits
- **Full Tweet Management**: Post, search, and delete tweets programmatically
- GitHub: https://github.com/mbelinky/x-mcp-server
- NPM: https://www.npmjs.com/package/@mbelinky/x-mcp-server
The server is actively maintained and was built …

Add X (Twitter) MCP server

---

README.md

Added Peliqan

---

README.md

Adding PiloTY to the awesome MCP servers list.
**PiloTY** is an MCP server that enables AI agents to control interactive terminals like humans, providing:
- Stateful terminal sessions with persistent context
- SSH connections with public key authentication  
- Background process management and monitoring
- Interactive program handling (SSH, shell interactions)
- Comprehensive session logging for debugging
- Repository: https://github.com/yiwenlu66/PiloTY
- Technical Design: https://github.com/yiwenlu66/PiloTY/blob/main/TECHNICAL.md
PiloTY bridges the gap between AI agents and terminal interfaces through the Model Context Protocol, making complex terminal workflows accessible through natural language.

Add PiloTY - AI Terminal Control MCP Server

---

README.md

This PR adds the Storyblok MCP Server to the community servers list.
The Storyblok MCP server enables your AI assistants to directly access and manage your Storyblok spaces, stories, components, assets, workflows, and more.
- Full Storyblok Management: CRUD for stories, components, assets, datasources, tags, releases, workflows, and more.(Covered everything)
- Modular Tooling: Each Storyblok resource is managed by its own tool module for easy extension and maintenance.
- Meta Tool: Discover all available tools and their descriptions at runtime.
- Async & Fast: Built on httpx and FastMCP for high performance.
- Environment-based Config: Securely manage tokens and space IDs via .env.
- Bulk Operations: Efficiently update, delete, or publish multiple resources at once.
URL: …

Add Storyblok MCP Server 

---

README.md

- [X ] Place the newly added server in the right position alphabetically.
This MCP server provides three main tools that fetch data from the Agile Luminary API:
📚 getRelatedDocuments
Purpose: Retrieve related documents based on a search string
Parameters: searchString (required) - The text to search for in documents
Use Case: Find relevant documentation and specifications related to your current work
📋 getCurrentWork
Purpose: Fetches work currently assigned to the user
Parameters: None
Use Case: See what tasks and user stories are actively assigned to you
🔍 getPastWork
Purpose: Retrieves completed work related to user stories based on search criteria
Parameters: searchString (required) - Search term to find relevant past work
Use Case: Review historical context and completed tasks for …

Adding Agile Luminary to the registry

---

README.md

Add Inspektor Gadget MCP server

---

README.md

Slightly changed the name of the submitted MCP server

Small name change of Alby MCP server

---

README.md

What is Octocode? 🐙
The perfect code assistant that can help understand anything. Octocode was built to understand connections between Github repositories and NPM packages under any privilege level you have. With AI-powered advanced search, heuristic discovery, and smart fallbacks, it makes GitHub's vast repository of knowledge truly searchable and analyzable.
It already integrated into
https://github.com/modelcontextprotocol/servers
You can visit here to learn more:
http://octocode.ai/
Server Details
This server knows to do smart code research and using users privileges (npm & github) to fetch and analysis code and docs in real time! Motivation and Context
It started as a personal tool while working at Wix to solve the challenge of navigating large private/public codebases and keeping up …

Update README.md - add octocode

---

README.md

Add `reminder-mcp`

---

README.md

Add Shadcn Registry Manager

---

README.md

Add Vpuna AI Search MCP server

---

README.md

GoLogin MCP Server
Manage your GoLogin browser profiles and automation directly through AI conversations. This MCP server connects to the GoLogin API, letting you create, configure, and control browser profiles using natural language.

Add GoLogin MCP server

---

README.md

Add official Mux MCP server

---

README.md

**A Model Context Protocol MCP server for capturing website screenshots with full page, element, and device size features.**
- **Full-page screenshot capture** with automatic scrolling
- **Element-specific screenshots** using CSS selectors
- **Multiple device presets** (mobile, tablet, desktop)
- **Custom viewport configurations**
- **Advanced wait conditions** (CSS selectors, network idle, custom delays)
- **Error handling and validation** for secure operation
- **Rate limiting** to prevent resource exhaustion

Adding ScreenshotMCP

---

README.md

Add PaddleOCR MCP server

---

README.md

Add FHIR MCP Server for healthcare data management and clinical workflow integration.
Add new MCP Server for FHIR-compliant healthcare systems, enabling seamless interaction between LLM-based agents and clinical data backends. The server provides comprehensive CRUD operations on FHIR resources, intelligent document processing with semantic search capabilities, and LOINC terminology integration. Built on FastMCP framework with Docker support, it includes OAuth2 authentication, vector-based document search via Pinecone, and supports multiple document formats (TXT, CSV, JSON, PDF) for RAG-ready clinical data queries.
Provide healthcare developers and clinical teams with a standardized interface to query and manipulate FHIR clinical data using natural language prompts, enabling efficient …

Add FHIR MCP Server

---

README.md

Add Kiwi.com MCP server

---

README.md

Added Powertool mcp server

---

README.md

Added server mcp.stromhaltig.de

---

README.md

add AutoGen documentation MCP server to the list

---

README.md

Added 1mcpserver: A server to automatically find and commit changes locally

---

README.md

Add VinciGit00 MCP server

---

README.md

Added Official ThingsBoard MCP Server

---

README.md

https://github.com/xxczaki/local-history-mcp
> Access Cursor/VS Code Local History through the Model Context Protocol for AI-powered data recovery

Add local-history-mcp

---

README.md

Add byQuexo MCP server

---

README.md

- [ x] Place the newly added server in the right position alphabetically.

/README.md: add dolt-mcp

---

README.md

Added fast-filesystem-mcp to Community Servers section.
This MCP server provides.
- Advanced filesystem operations with Claude-optimized performance
- Large file handling capabilities with streaming support
- Sequential reading for large files with continuation tokens
- Comprehensive directory operations and file search
- Automatic backup and recovery features
- Enterprise-grade stability and overflow protection
Repository: https://github.com/efforthye/fast-filesystem-mcp
NPM Package: https://www.npmjs.com/package/fast-filesystem-mcp

docs: Add fast-filesystem-mcp server

---

README.md

**Description**
This PR adds the  gluestack-ui-mcp-server server to the Community Servers section of the awesome-mcp-servers list.
**About Gluestack-ui-mcp-server** 
The MCP server is tailored for React Native–first development using Gluestack UI. In essence, it enables AI assistants (like Claude Desktop, Cursor, Continue.dev, etc.) to access Gluestack UI components, source code, and documentation directly through MCP tooling.
**Features :** 
React Native–First and Cross-Platform Support
Designed for universal experiences across iOS, Android, and web, with seamless integration into Expo workflows, plus built-in support for React Native Navigation (stack, tab, drawer).
[GitHub](https://github.com/gauravsaini/gluestack-ui-mcp-server)
Component Variants
Supports multiple styling and …

Add gluestack ui mcp server

---

README.md

Added Postman official MCP server to the directory

Add official Postman MCP server.md

---

README.md

Add Sourcerer MCP

---

README.md

Add KnowAir Weather MCP server

---

README.md

Add: run-sql-connectorx (ConnectorX SQL → CSV/Parquet MCP server)

---

README.md

Add Zenable MCP Server

---

README.md

Add Render MCP server

---

README.md

Add new server "context-awesome" to Community Servers.

Add new server context-awesome

---

README.md

Add 4everhosting mcp [Here](https://github.com/4everland/4everland-hosting-mcp) is the source

Add 4everhosting mcp

---

README.md

Add Chroma Package Search MCP server

---

README.md

add AnyCrawl MCP Server

---

README.md

Adding Poland KRS

---

README.md

This pull request adds [Openfort's](https://www.openfort.io/) MCP Server to the list of official available Model Context Protocol servers.
Openfort is an open source alternative to wallet infrastructure solutions, it supercharges projects with authentication, user management and payments.
Openfort’s MCP Server is a plug-and-play solution that enhances AI assistants by enabling them to create projects, manage configurations, and query data automatically when building applications on Openfort's infrastructure. 
Key Features:
- 🔐 Authentication — Directly authenticate from just plugging in the MCP
- 📄️ Initialize — Create new Openfort projects from the chat
- 🏗️ Scaffold — Build new apps from scratch using a single prompt
- 🔎 Context — Query the latest version of the documentation
- 💳️ …

Add Openfort MCP server

---

README.md

Add new MCP provider

---

README.md

Added AllInOneMCP MCP server

---

README.md

- Added ShopSavvy MCP Server to the Official Servers section
- Complete product and pricing data solution for AI assistants
- Published as `@shopsavvy/mcp-server` npm package
- 🔍 **Product Search**: Lookup by barcode, ASIN, URL, model number, or ShopSavvy ID
- 📊 **Pricing Intelligence**: Current pricing data from thousands of retailers
- 📈 **Price History**: Historical pricing trends and tracking
- 🔄 **Automated Monitoring**: Schedule products for automatic price refresh
- 📋 **Detailed Metadata**: Comprehensive product information beyond just pricing
- 🎯 **API Usage Tracking**: Monitor credit consumption and usage statistics
ShopSavvy provides a comprehensive e-commerce data API that enables AI assistants to access real product and pricing information. This fills a gap in the current …

Add ShopSavvy MCP Server for comprehensive product and pricing data

---

README.md

docs: add azure devops mcp

---

README.md

Add Homey MCP Server
