wong2/awesome-mcp-servers

README.md

- Remove '[' from BigQuery link

chore:fix hyperlink for BigQuery

---

README.md

Add entry for Windows CLI MCP Server to the README.md file.
* Add a new entry under the Community Servers section for the Windows CLI MCP Server.
* Include a link to the repository `[https://github.com/SimonB97/win-cli-mcp-server`](https://github.com/SimonB97/win-cli-mcp-server%60).

Add entry for Windows CLI MCP Server

---

README.md

This PR adds a link to a new community implementation that provides BigQuery integration capabilities. The server is maintained in its own repository at https://github.com/ergut/mcp-bigquery-server and is available via npm.

Add BigQuery Server to Community Implementations

---

README.md

The current list of community servers has lots of data sources but seems to be missing any sort of data visualization tools. While Claude Desktop natively renders Recharts visualizations well, it would be beneficial to have a way to produce charts in a canonical MCP-like way (especially for alternative clients). mcp-vegalite-server meets this requirement.

Added mcp-vegalite-server

---

README.md

Add Metoro - https://metoro.io/ - to the list of official integrations. We built an MCP server - https://github.com/metoro-io/metoro-mcp-server - for Metoro which allows MCP clients to directly query  the status of their Kubernetes clusters and all workloads running inside using natural language.

Add Metoro MCP Server

---

README.md

Add mamertofabian/mcp-everything-search to community servers. This server provides:
- Fast file search capabilities using Everything SDK
- Windows-specific implementation
- Complements existing filesystem servers with specialized search functionality

Update README.md - Add Everything Search to community servers

---

README.md

This PR adds the mcphub.nvim, a powerful Neovim plugin that integrates MCP (Model Context Protocol) servers into your workflow. Configure and manage MCP servers through a centralized config file while providing an intuitive UI for testing tools and resources. Perfect for LLM integration, offering both programmatic API access and interactive testing capabilities through the :MCPHub command.
* Added client under MCP Clients section

Add mcphub.nvim

---

README.md

This change adds the Australian Pharmaceutical Benefits Scheme (PBS) API MCP Server to the Community Servers section.
The PBS API MCP Server provides:
- Access to Australian pharmaceutical data through natural language queries
- Built with Python and FastAPI
- Comprehensive information about medicine pricing and availability for medical professionals, saas operators and integrators

Add PBS API MCP Server to Community Servers

---

README.md

[QGIS MCP](https://github.com/jjsantos01/qgis_mcp) connects QGIS to Claude AI through the Model Context Protocol (MCP), allowing Claude to directly interact with and control QGIS. This integration enables prompt assisted project creation, layer loading, code execution and more.

docs: Add QGIS MCP server to README

---

README.md

PR to add Rootly MCP server, which allows responders to manage their incident directly in their IDE

Rootly MCP server

---

README.md

This PR adds a new entry for the Binary Ninja MCP server implementation.  It is useful for connecting Binary Ninja with your favorite MCP client to aid in reverse engineering of software binaries.
- https://github.com/fosdickio/binary_ninja_mcp
- https://binary.ninja

Add Binary Ninja MCP server

---

README.md

Add "Mailtrap" to the list of official MCPs

---

README.md

Added community MCP Slack server to the README
Unlike the "reference server" version of the Slack MCP, proposed MCP server supports stdio and sse transports, proxy settings and in my opinion, most important it does not require bot/apps being created in the Slack Workspace that will require approvals so it is possible to setup MCP server fully for yourself on behalf your own account.

Proposal to add community MCP Slack server to the README

---

README.md

**Reason for Addition:**
Working with large OpenAPI or Swagger specifications can quickly consume context window limits. This server solves that problem by providing **token-efficient access** to API specs via MCP Resources.
Instead of loading the entire file, users can interactively explore API paths, operations, and components using intuitive URIs (`openapi://...`). It supports local files and remote URLs, automatically handles Swagger v2 conversion, and transforms internal references into clickable links, making API understanding and exploration significantly faster and more context-friendly.

Add OpenAPI Schema Explorer MCP server

---

README.md

Anthropic has handed development of the [GitHub MCP server](https://github.com/github/github-mcp-server) over to GitHub. We have placed a [deprecation notice](https://github.com/modelcontextprotocol/servers/tree/main/src/github#github-mcp-server) on the old repo to redirect to the official server. The official server _is_ already listed, so this just removes the link to the out of date server.

remove deprecated github reference server

---

README.md

Added a new MCP server for Terragrunt, for fetching up-to-date official documentation.

refactor: add terragrunt docs mcp-server reference

---

README.md

Add mcp-open-library to the README.
mcp-open-library is a Model Context Protocol (MCP) server for the Open Library API that enables AI assistants to search for book and author information.

Add mcp-open-library to the README

---

README.md

Add CRIC Wuye AI official MCP Server. 
**CRIC Wuye AI** (CRIC物业AI) is an intelligent assistant developed by [CRIC](http://www.cricchina.com/) specifically for the property management industry. It was [officially launched](https://mp.weixin.qq.com/s/GC4V1M6N199Ay2f3kZan_Q) on April 25, 2025.
*P.S. CRIC is the top Industry Research & Database Provider in Real Estate Sector of China. Wuye (物业) means Property Management in Chinese.*
Leveraging a combination of industry knowledge base construction, multimodal large models, and RAG technology, **CRIC Wuye AI** integrates five core capability modules: **Industry Research**, **Laws & Regulations**, **Community Governance**, **Project Operations**, and **Content Writing**. It also expands into two smart agents focused on **News & Public Opinion** …

Add CRIC Wuye AI official MCP Server

---

README.md

Baserow launched their embedded MCP server in version 1.33 (https://baserow.io/blog/baserow-1-33-release-notes).

Add Baserow

---

README.md

This PR adds Language Server (https://github.com/isaacphi/mcp-language-server) to the community servers list.
The Language Server MCP server helps MCP enabled clients navigate codebases more easily by giving them access to semantic tools like get definition, references, rename, and diagnostics.

Add Language Server to community servers list

---

README.md

added Memory-Plus to the list of community-developed MCP servers

Add Memory-Plus to the list of community-developed MCP servers 

---

README.md

We just launched a free remote MCP server for DeepWiki (https://deepwiki.com/).

Update README.md with DeepWiki MCP server

---

README.md

Added Knit MCP server entry with access to 10,000+ tools across HRIS, ATS, CRM, Accounting, Calendar, Meeting, Ticketing, and more categories.

Add Knit MCP server to Official Servers section

---

README.md

Add OSV MCP Server to Community Servers section.
Provides access to OSV (Open Source Vulnerabilities) database for vulnerability queries by package version or commit, batch operations, and detailed vulnerability information by ID.
Repository: https://github.com/StacklokLabs/osv-mcp

Add OSV MCP Server

---

README.md

Please consider adding WayStation to the list of remote MCP servers. WayStation MCP seamlessly connects Claude (and other clients) to a broad range of productivity tools, including Notion, Monday, AirTable, etc.
A few notes:
- WayStation MCP supports both Streamable HTTPS and SSE transports
- The default endpoint at https://waystation.ai/mcp does transport negotiation and authorization if necessary
- WayStation also provides preauthenticated individual endpoints like https://waystation.ai/mcp/Iddq66dIdkfARDNb3K. Any registered user can get one at https://waystation.ai/connect/mcp-server/guide
- The server was tested with Claude, Cursor, Cline, WindSurf, and MCP-remote
Thanks for consideration!

Added WayStation server to the list

---

README.md

This is the official [SonarQube MCP Server](https://github.com/SonarSource/sonarqube-mcp-server) by Sonar.

Add SonarQube MCP Server to Official Servers

---

README.md

Move Token Metrics MCP to Official Servers list from Community Servers list

Update README.md - Move Token Metrics MCP to Official Servers

---

README.md

Adding SchemaFlow to the awesome MCP servers list.
**What it does:**
- Provides real-time PostgreSQL & Supabase schema access via MCP
- Enables AI-IDEs to get live database context for smarter code generation
- Supports Server-Sent Events (SSE) for real-time updates
**Links:**
- GitHub: https://github.com/CryptoRadi/schemaflow-mcp-server
- Website: https://schemaflow.dev
- Documentation: https://schemaflow.dev/mcp-guide
**Supported AI-IDEs:**
- Cursor
- Windsurf  
- VS Code + Cline
This server helps developers by providing their AI coding assistants with up-to-date database schema information, enabling more accurate code generation and database queries.

Add SchemaFlow MCP Server

---

README.md

Added FrankfurterMCP -- an interface to the Frankfurter API for currency exchange data -- to the list of community servers.

Added FrankfurterMCP community server

---

README.md

Adding consult7 - an MCP server that enables AI agents to analyze large codebases and document collections using high-context models via OpenRouter, OpenAI, or Google AI. Particularly useful with Claude Code for analyzing projects that exceed the context window limits.

Add consult7 MCP server

---

README.md

This PR adds [anki-connect-mcp](https://github.com/spacholski1225/anki-connect-mcp) to the list of MCP servers in `README.md`.
- The server integrates with Anki using the AnkiConnect add-on.
- It enables AI assistants and other MCP clients to interact with flashcard collections.
- Entry added in alphabetical order, following the existing list format.

Update README about MCP for Anki

---

README.md

Adding the official Harness.io MCP Server to this list, we are on other MCP Registry websites and would like to be included here as well.

Update MCP Server List to include Harness.io

---

README.md

The server currently provides the following tools for LLM interaction:
- get_api_status(): Check if the Cal.com API key is configured in the environment. Returns a string indicating the status.
- list_event_types(): Fetch a list of all event types from Cal.com for the authenticated account. Returns a dictionary with the list of - - event types or an error message.
- get_bookings(...): Fetch a list of bookings from Cal.com, with optional filters (event_type_id, user_id, status, date_from, date_to, limit). Returns a dictionary with the list of bookings or an error message.
- create_booking(...): Create a new booking in Cal.com for a specific event type and attendee. Requires parameters like start_time, attendee details, and event type identifiers. Returns a dictionary with booking details …

Add calcom community server

---

README.md

Adds the official [IPLocate MCP Server](https://github.com/iplocate/mcp-server-iplocate) to the readme.

Add IPLocate MCP Server to Official Servers

---

README.md

Maven Tools provides enhanced Maven Central integration with intelligent caching, bulk operations, and version classification for AI assistants.

Add Maven Tools MCP server to community servers list

---

README.md

[Nebula-Block-Data/nebulablock-mcp-server](https://github.com/Nebula-Block-Data/nebulablock-mcp-server)  - integrates with the fastmcp library to expose the full range of NebulaBlock API functionalities as accessible tools
This server integrates with the fastmcp library to expose the full range of [NebulaBlock](https://www.nebulablock.com/) API functionalities as accessible tools, enabling seamless and efficient interaction within any MCP-compatible environment.

add Nebula block MCP server

---

README.md

- Added Bing Webmaster Tools MCP server to the Community Servers section
- Placed alphabetically between BigQuery and Binary Ninja entries
- Provides access to Bing Webmaster Tools API for search analytics, site management, URL submission, and SEO insights
This MCP server enables AI assistants to interact with Bing Webmaster Tools, providing access to most of the API endpoints for SEO management and site analytics.
Repository: https://github.com/isiahw1/mcp-server-bing-webmaster

Add Bing Webmaster Tools MCP server

---

README.md

Add official Mercado Libre MCP Server (http://mcp.mercadolibre.com/).
Add new official MCP Server for Mercado Libre, to enhance developer experience integrating with Mercado Libre solutions.
Server is hosted remotely by Mercadolibre supporting new Streamable HTTP Transport.
Details on how to connect to the server and example use cases are provided in [Mercado Libre's MCP Server doc site](http://mcp.mercadolibre.com/).
Provide official MCP Server for Mercado Libre to enhance developers experience integrating with this platform.
Integration with the server was tested from several clients, including: Cursor, Windsurf, Cline and Claude Desktop.

Add Mercado Libre's official MCP Server

---

README.md

This PR adds the Project Manager MCP Server to the community servers list.
The Project Manager MCP server enables hierarchical task management with a structured workflow from ideas to epics to tasks, featuring a CLI dashboard for project visualization.
- Hierarchical task management (ideas → epics → tasks)
- CLI dashboard for project visualization
- NPX-ready deployment
- Compatible with Claude Desktop, Cursor, VS Code + Copilot, Continue.dev
- **URL**: https://github.com/croffasia/mcp-project-manager
- **License**: MIT
- **Language**: TypeScript/JavaScript

Add Project Manager MCP Server

---

README.md

Hi there!
I'm the author of MCPJungle - a self-hosted MCP Gateway to connect MCP clients to servers.
It is suitable for individual developers to run on their local machines or enterprises to run on their internal servers for centralized management.
Happy to answer any questions.
Cheers!

Add MCPJungle gateway to Community Servers

---

README.md

This PR adds **Spotify Player** (Python) to the *Community Servers* section.
- Repo: https://github.com/vsaez/mcp-spotify-player
- What it does: Control Spotify playback, queue, volume and playlists from Claude/Cursor via MCP.
- Why useful: Provides a practical, user-facing media integration demonstrating MCP tools end-to-end (search, playback, queue management, diagnostics).

Add Spotify Player (Python) – control Spotify via MCP

---

README.md

MCP server that provides programmatic access to the Israeli Central Bureau of Statistics (CBS) price indices and economic data

Add Israel Statistics MCP

---

README.md

Druid MCP Server - STDIO/SEE MCP Server for Apache Druid by iunera that provides extensive tools, resources, and prompts for managing and analyzing Druid clusters.

Add druid mcp server
